val _ = load "BinIO"
val _ = load "TextIO"
val _ = load "Byte"
val _ = load "Int"
val _ = load "Word8"
val _ = load "Word8Vector"
val _ = load "Array"
val _ = load "String"
val _ = load "StringCvt"

val _ = use "poly_smlnj.sml"